service: scrape-covid-india
provider:
  name: aws
  runtime: python3.8
  credentials:
      accessKeyId: ###
      secretAccessKey: ###

package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  scrape:
    handler: handler.main